apiVersion: v1
kind: Service
metadata:
  name: nginx-service # name of the service
spec: # same as previous , you identify the pods wth this
  selector:
    app: nginx
  ports: # start the configuration to expose the port
    - protocol: TCP # define the protocol
      port: 80 # WHICH port are you exposing to the container
      targetPort: 80 #which port are you exposing to the client
      nodePort: 30007 # this port can be valid port whitin the node
  type: NodePort # one of the ports, 

  